"""campos personalizados de libros

Revision ID: 95af4396bdae
Revises: 0007_imagenes_libro
Create Date: 2026-09-13 20:43:09.403321
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95af4396bdae'
down_revision: Union[str, None] = '0007_imagenes_libro'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campos_libro',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('etiqueta', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requerido', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='uq_campo_libro_codigo')
    )
    op.create_index(op.f('ix_campos_libro_codigo'), 'campos_libro', ['codigo'], unique=False)
    op.add_column('libros', sa.Column('datos_extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # Nota: el autogenerate también detectó drift preexistente del índice/constraint
    # único de `libros.isbn` (ajeno a este cambio). Se omite a propósito para que
    # esta migración quede acotada a los campos personalizados.


def downgrade() -> None:
    op.drop_column('libros', 'datos_extra')
    op.drop_index(op.f('ix_campos_libro_codigo'), table_name='campos_libro')
    op.drop_table('campos_libro')
